blank_issues_enabled: false
contact_links:
    - name: RHEN Discord
      url: https://discord.gg/the-crew
      about: Join our Discord for general questions as well as direct contact with the developers
